# Generated by Django 4.2.29 on 2026-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('playlist', 'Playlist'), ('do_not_play', 'Do Not Play')], default='playlist', max_length=20)),
                ('moment', models.CharField(choices=[('ceremony', 'Ceremony'), ('cocktail', 'Cocktail Hour'), ('first_dance', 'First Dance'), ('reception', 'Reception'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['list_type', 'moment', 'order', 'created_at'],
            },
        ),
    ]
