version: "3"
services:
  # WARNING: If you want to use this docker-compose file in production, you need to backup your database!
  wedding:
    container_name: wedding
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    ports:
      - 8080:8080
    volumes:
      - ./media:/app/media
    restart: unless-stopped
