# Generated by Django 4.2.29 on 2026-03-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Guest's name (optional)", max_length=100)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(default='Drake & Shawna', max_length=100)),
                ('bride_name', models.CharField(default='Shawna Beckstead', max_length=100)),
                ('groom_name', models.CharField(default='Drake Bridgewater', max_length=100)),
                ('hero_title', models.CharField(default='The Bridgewaters!!', max_length=200)),
                ('wedding_date_display', models.CharField(blank=True, help_text='Human-readable date shown on the site, e.g. "June 14, 2026"', max_length=100)),
                ('wedding_location', models.CharField(blank=True, max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID, e.g. UA-XXXXXXXX-1 or G-XXXXXXXXXX', max_length=50)),
            ],
            options={
                'verbose_name': 'Wedding Settings',
                'verbose_name_plural': 'Wedding Settings',
            },
        ),
    ]
