# Generated by Django 4.2.29 on 2026-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_deadline',
            field=models.DateField(blank=True, help_text='Deadline for guests to RSVP. Used to flag overdue responses on the dashboard.', null=True),
        ),
    ]
