# Generated by Django 4.2.29 on 2026-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='hero_photo',
            field=models.ImageField(blank=True, help_text='Hero photo shown on the home page. Overrides the default static image.', null=True, upload_to='site/'),
        ),
    ]
