# Generated by Django 4.2.29 on 2026-03-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_weddingsettings_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='theme',
            field=models.CharField(choices=[('rose', 'Rose'), ('blush', 'Blush'), ('sage', 'Sage'), ('navy', 'Navy'), ('gold', 'Gold'), ('slate', 'Slate'), ('mauve', 'Mauve'), ('terra', 'Terra')], default='rose', help_text='Color theme for the public-facing website.', max_length=20),
        ),
    ]
