# Generated by Django 4.2.29 on 2026-03-21 01:35

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_THEMES = [
    {'name': 'Rose',  'accent': '#e11d48', 'accent_hover': '#9f1239', 'accent_light': '#fce7f3'},
    {'name': 'Blush', 'accent': '#c084a0', 'accent_hover': '#9d4f78', 'accent_light': '#fdf4ff'},
    {'name': 'Sage',  'accent': '#4d7c4f', 'accent_hover': '#2d5a2e', 'accent_light': '#f0fdf4'},
    {'name': 'Navy',  'accent': '#1e3a5f', 'accent_hover': '#0f1f38', 'accent_light': '#eff6ff'},
    {'name': 'Gold',  'accent': '#b45309', 'accent_hover': '#78350f', 'accent_light': '#fffbeb'},
    {'name': 'Slate', 'accent': '#475569', 'accent_hover': '#1e293b', 'accent_light': '#f8fafc'},
    {'name': 'Mauve', 'accent': '#7c3f6e', 'accent_hover': '#4a1942', 'accent_light': '#fdf2f8'},
    {'name': 'Terra', 'accent': '#c2714f', 'accent_hover': '#8c4a30', 'accent_light': '#fff7ed'},
]


def seed_themes(apps, schema_editor):
    Theme = apps.get_model('wedding', 'Theme')
    for t in DEFAULT_THEMES:
        Theme.objects.get_or_create(name=t['name'], defaults=t)


def unseed_themes(apps, schema_editor):
    apps.get_model('wedding', 'Theme').objects.filter(
        name__in=[t['name'] for t in DEFAULT_THEMES]
    ).delete()


def set_default_theme(apps, schema_editor):
    # WeddingSettings.theme is now a FK — point the singleton at Rose
    Theme = apps.get_model('wedding', 'Theme')
    WeddingSettings = apps.get_model('wedding', 'WeddingSettings')
    rose = Theme.objects.filter(name='Rose').first()
    if rose:
        WeddingSettings.objects.filter(pk=1).update(theme_id=rose.pk)


def unset_default_theme(apps, schema_editor):
    apps.get_model('wedding', 'WeddingSettings').objects.filter(pk=1).update(theme_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_add_theme_to_wedding_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Rose"', max_length=50, unique=True)),
                ('accent', models.CharField(help_text='Primary accent color in hex, e.g. #e11d48', max_length=7)),
                ('accent_hover', models.CharField(help_text='Darker shade used on hover, e.g. #9f1239', max_length=7)),
                ('accent_light', models.CharField(help_text='Light tint used for backgrounds, e.g. #fce7f3', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_themes, unseed_themes),
        migrations.AlterField(
            model_name='weddingsettings',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Color theme for the public-facing website. Create new themes in the Themes section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wedding.theme'),
        ),
        migrations.RunPython(set_default_theme, unset_default_theme),
    ]
