# Generated by Django 4.2.29 on 2026-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_theme_model_and_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Contributor's name (optional)", max_length=100)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='cashapp_handle',
            field=models.CharField(blank=True, help_text='Cash App cashtag, e.g. $YourName', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='paypal_handle',
            field=models.CharField(blank=True, help_text='PayPal.me link or username, e.g. YourName', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venmo_handle',
            field=models.CharField(blank=True, help_text='Venmo username, e.g. @YourName', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='zelle_handle',
            field=models.CharField(blank=True, help_text='Zelle email or phone number', max_length=100),
        ),
    ]
