# Generated by Django 4.2.29 on 2026-05-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_pagesectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='contact_intro',
            field=models.TextField(blank=True, help_text='"Get in Touch" section intro sentence.'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='honeymoon_description',
            field=models.TextField(blank=True, help_text='Short blurb below the title.'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='honeymoon_title',
            field=models.CharField(blank=True, help_text='Card heading, e.g. "Our Honeymoon Adventure"', max_length=200),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='proposal_divider_photo',
            field=models.ImageField(blank=True, help_text='Banner photo shown above The Proposal section. Falls back to the default scenic image.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='questions_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle shown below "Ask Us Anything".'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='registry_button_label',
            field=models.CharField(blank=True, help_text='CTA button text, e.g. "View Registry"', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='registry_description',
            field=models.TextField(blank=True, help_text='Short blurb below the title.'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='registry_title',
            field=models.CharField(blank=True, help_text='Card heading, e.g. "Our Wish List"', max_length=200),
        ),
    ]
