# Generated by Django 5.2.16 on 2026-07-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_configurable_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='wedding_datetime',
            field=models.DateTimeField(blank=True, help_text="Exact ceremony date & time, used to drive the countdown timers. Enter the venue's local wall-clock time — treated as literal local time in each visitor's browser (not converted between timezones).", null=True),
        ),
    ]
