# Generated by Django 4.2.29 on 2026-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickTickSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=200)),
                ('username', models.EmailField(blank=True, help_text='TickTick account email', max_length=254)),
                ('password', models.CharField(blank=True, help_text='TickTick account password. Stored in the database — ensure your admin is accessed over HTTPS in production.', max_length=200)),
                ('project_name', models.CharField(default='Wedding', help_text='Name of the TickTick project to sync (case-insensitive).', max_length=100)),
                ('drake_assignee_id', models.CharField(blank=True, help_text='TickTick assignee ID for Drake. Run `manage.py ticktick_auth` to find this value.', max_length=200)),
                ('shawna_assignee_id', models.CharField(blank=True, help_text='TickTick assignee ID for Shawna. Run `manage.py ticktick_auth` to find this value.', max_length=200)),
            ],
            options={
                'verbose_name': 'TickTick Settings',
                'verbose_name_plural': 'TickTick Settings',
            },
        ),
    ]
