# Generated by Django 4.2.29 on 2026-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_tickticksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_cols', models.PositiveIntegerField(default=20)),
                ('grid_rows', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Seating Config',
                'verbose_name_plural': 'Seating Config',
            },
        ),
        migrations.CreateModel(
            name='SeatingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=8)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square')], default='round', max_length=10)),
                ('grid_x', models.IntegerField(default=0, help_text='Left column (0-indexed)')),
                ('grid_y', models.IntegerField(default=0, help_text='Top row (0-indexed)')),
                ('grid_width', models.PositiveIntegerField(default=2, help_text='Width in grid cells')),
                ('grid_height', models.PositiveIntegerField(default=2, help_text='Height in grid cells')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
