# Generated by Django 4.2.29 on 2026-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_seatingconfig_seatingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingconfig',
            name='cell_size_ft',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Real-world size of one grid cell in feet.', max_digits=5),
        ),
    ]
