# Generated by Django 4.2.29 on 2026-03-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_add_cell_size_ft_to_seating_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(help_text='e.g. "Wedding Day", "Rehearsal Dinner"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='WeddingPartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('maid_of_honor', 'Maid of Honor'), ('best_man', 'Best Man'), ('bridesmaid', 'Bridesmaid'), ('groomsman', 'Groomsman'), ('other', 'Other')], max_length=20)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color used to identify this person in the schedule UI.', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes. Must be a multiple of 15.')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('getting_ready', 'Getting Ready'), ('ceremony', 'Ceremony'), ('photos', 'Photos'), ('reception', 'Reception'), ('travel', 'Travel'), ('meal', 'Meal'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='planning.weddingpartymember')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planning.scheduleday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
