# Generated by Django 4.2.29 on 2026-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_scheduleday_weddingpartymember_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingpartymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='weddingpartymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='WeddingPartyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='planning.weddingpartymember')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
