# Generated by Django 6.0.3 on 2026-03-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticktick_id', models.CharField(max_length=200, unique=True)),
                ('project_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('due_date', models.CharField(blank=True, max_length=50)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('created_time', models.CharField(blank=True, max_length=50)),
                ('modified_time', models.CharField(blank=True, max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TickTickSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=200)),
                ('username', models.EmailField(blank=True, help_text='TickTick account email', max_length=254)),
                ('password', models.CharField(blank=True, help_text='TickTick account password. Stored in the database — ensure your admin is accessed over HTTPS in production.', max_length=200)),
                ('project_name', models.CharField(default='Wedding', help_text='Name of the TickTick project to sync (case-insensitive).', max_length=100)),
                ('drake_assignee_id', models.CharField(blank=True, help_text='TickTick assignee ID for Drake. Run `manage.py ticktick_auth` to find this value.', max_length=200)),
                ('shawna_assignee_id', models.CharField(blank=True, help_text='TickTick assignee ID for Shawna. Run `manage.py ticktick_auth` to find this value.', max_length=200)),
            ],
            options={
                'verbose_name': 'TickTick Settings',
                'verbose_name_plural': 'TickTick Settings',
            },
        ),
    ]
