# Generated by Django 4.2.29 on 2026-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticktick_id', models.CharField(max_length=200, unique=True)),
                ('project_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('due_date', models.CharField(blank=True, max_length=50)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('created_time', models.CharField(blank=True, max_length=50)),
                ('modified_time', models.CharField(blank=True, max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
