# Generated by Django 4.2.29 on 2026-03-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show this event on the public wedding program page'),
        ),
    ]
