# Generated by Django 6.0.3 on 2026-03-19 05:32

import django.db.models.deletion
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('formal', 'Formal'), ('fun', 'Fun'), ('family', 'Family'), ('work', 'Work')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('save_the_date_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('save_the_date_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('invitation_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('invited', 'Invited'), ('not_invited', 'Not invited')], default='planned', max_length=15)),
                ('rehearsal_dinner', models.BooleanField(default=False)),
                ('is_attending', models.BooleanField(default=None, null=True)),
                ('rsvp_responded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('side', models.CharField(blank=True, choices=[('bride', "Bride's side"), ('groom', "Groom's side"), ('both', 'Both')], max_length=10)),
                ('plus_one_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('is_attending', models.BooleanField(default=None, null=True)),
                ('meal', models.CharField(blank=True, choices=[('beef', 'beef'), ('fish', 'fish'), ('hen', 'chicken'), ('vegetarian', 'vegetarian')], max_length=20, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('seat_color', models.CharField(blank=True, default='', max_length=20)),
                ('seating_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='seating.seatingtable')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.party')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingPartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('maid_of_honor', 'Maid of Honor'), ('best_man', 'Best Man'), ('bridesmaid', 'Bridesmaid'), ('groomsman', 'Groomsman'), ('other', 'Other')], max_length=20)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color used to identify this person in the schedule UI.', max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('guest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_party_info', to='guests.guest')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeddingPartyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='guests.weddingpartymember')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
