# Generated by Django 4.2.29 on 2026-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='plus_one_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='rsvp_responded_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='side',
            field=models.CharField(blank=True, choices=[('bride', "Bride's side"), ('groom', "Groom's side"), ('both', 'Both')], max_length=10),
        ),
    ]
