# Generated by Django 4.2.29 on 2026-03-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_dietary_restrictions_party_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('invited', 'Invited'), ('not_invited', 'Not invited')], default='planned', max_length=15),
        ),
    ]
