# Generated by Django 6.0.3 on 2026-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_party_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='plus_one_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of unnamed +1 guests attending with this party.'),
        ),
    ]
