# Generated by Django 6.0.3 on 2026-03-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_party_plus_one_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('formal', 'Formal'), ('fun', 'Fun'), ('family', 'Family'), ('work', 'Work')], default='', max_length=10),
        ),
    ]
