# Generated by Django 4.2.29 on 2026-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingpartymember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weddingpartymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='wedding_party/'),
        ),
    ]
