# Generated by Django 4.2.29 on 2026-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_weddingpartymember_bio_weddingpartymember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='wants_physical_card',
            field=models.BooleanField(default=False),
        ),
    ]
