# Generated by Django 4.2.29 on 2026-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_weddingpartymember_is_informed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTheDateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='email-images/save-the-date/')),
                ('background_color', models.CharField(default='#fff3e8', max_length=7)),
                ('font_color', models.CharField(default='#666666', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Save the date settings',
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='email-images/'),
        ),
    ]
