# Generated by Django 4.2.29 on 2026-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_email_template_image_save_the_date_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='footer_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
