# Generated by Django 4.2.29 on 2026-06-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_add_footer_html_to_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingpartymember',
            name='role',
            field=models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('maid_of_honor', 'Maid of Honor'), ('best_man', 'Best Man'), ('bridesmaid', 'Bridesmaid'), ('groomsman', 'Groomsman'), ('officiant', 'Officiant'), ('other', 'Other')], max_length=20),
        ),
    ]
