# Generated by Django 4.2.29 on 2026-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_add_officiant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weddingpartymember',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show this member on the public wedding party page.'),
        ),
        migrations.AlterField(
            model_name='weddingpartymember',
            name='is_informed',
            field=models.BooleanField(default=False, help_text='Has this person been informed that they are in the wedding party?'),
        ),
    ]
