# Generated by Django 4.2.29 on 2026-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_guest_label_member_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='background_color',
            field=models.CharField(default='#fff3e8', max_length=7),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='font_color',
            field=models.CharField(default='#666666', max_length=7),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='rsvp_button_color',
            field=models.CharField(default='#337ab7', max_length=7),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='rsvp_button_text',
            field=models.CharField(default='View Invitation', max_length=100),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='show_rsvp_button',
            field=models.BooleanField(default=True),
        ),
    ]
