# Generated by Django 4.2.29 on 2026-07-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0015_emailtemplate_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='purpose',
            field=models.CharField(choices=[('save_the_date', 'Save the Date'), ('invitation', 'Invitation'), ('other', 'Other')], default='other', help_text='Sending a Save the Date or Invitation template stamps the matching sent-date on each party automatically.', max_length=20),
        ),
    ]
