# Generated by Django 4.2.29 on 2026-07-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_emailtemplate_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options are hidden from the RSVP form but stay valid on existing guests.')),
            ],
            options={
                'ordering': ['ordering', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
