# Generated by Django 4.2.29 on 2026-03-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_seatingconfig_seatingtable'),
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='seating_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='planning.seatingtable'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('beef', 'beef'), ('fish', 'fish'), ('hen', 'chicken'), ('vegetarian', 'vegetarian')], max_length=20, null=True),
        ),
    ]
