# Generated by Django 5.2.16 on 2026-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_seed_meal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='address_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
