# Generated by Django 5.2.16 on 2026-07-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_party_address_city_party_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='ContactUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=list)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_updates', to='guests.party')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
