# Generated by Django 5.2.16 on 2026-07-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_guest_phone_contactupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='main_image_link',
            field=models.CharField(blank=True, choices=[('', '— no link —'), ('save_the_date', 'Save the Date page'), ('rsvp', 'RSVP / invitation'), ('details', 'Contact details form'), ('site', 'Wedding website')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='secondary_button_color',
            field=models.CharField(default='#b08d57', max_length=7),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='secondary_button_link',
            field=models.CharField(blank=True, choices=[('', '— no link —'), ('save_the_date', 'Save the Date page'), ('rsvp', 'RSVP / invitation'), ('details', 'Contact details form'), ('site', 'Wedding website')], default='save_the_date', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
