# Generated by Django 4.2.29 on 2026-03-20 18:37

from django.db import migrations

ITEMS = [
    # Booking & Contract
    ('Booking & Contract', 'Confirm deposit amount and payment schedule'),
    ('Booking & Contract', 'Understand cancellation / refund policy in writing'),
    ('Booking & Contract', "Ask how long they'll hold your date without a deposit"),
    ('Booking & Contract', 'Check if you must provide event liability insurance'),
    ('Booking & Contract', 'Review force majeure / weather clause'),
    ('Booking & Contract', 'Confirm legal name on contract matches your legal name'),

    # Pricing Gotchas
    ('Pricing Gotchas', 'Ask about overtime fees (cost per hour after end time)'),
    ('Pricing Gotchas', 'Ask about cake cutting fee'),
    ('Pricing Gotchas', 'Ask about corkage fee if bringing your own alcohol'),
    ('Pricing Gotchas', 'Confirm whether service charge & tax are included in quote'),
    ('Pricing Gotchas', 'Ask if vendor meals are required and at what cost'),
    ('Pricing Gotchas', 'Check if setup / teardown time is included or extra'),
    ('Pricing Gotchas', 'Confirm minimum guest count or food & beverage minimum'),

    # Logistics
    ('Logistics', 'Confirm vendor load-in / setup start time'),
    ('Logistics', 'Confirm hard cleanup / load-out deadline'),
    ('Logistics', 'Ask about noise curfew or amplified music cutoff time'),
    ('Logistics', "Confirm parking capacity and whether it's free"),
    ('Logistics', 'Ask if shuttle / valet service can be arranged'),
    ('Logistics', 'Ask when rehearsal access is available'),

    # Space & Facilities
    ('Space & Facilities', 'Confirm bridal suite availability and access time'),
    ('Space & Facilities', 'Ask about groom / groomsmen getting-ready space'),
    ('Space & Facilities', 'Check restroom count, accessibility, and proximity'),
    ('Space & Facilities', "Confirm ceremony + reception spaces don't overlap in time"),
    ('Space & Facilities', 'Ask about rain / weather backup plan (outdoor venues)'),
    ('Space & Facilities', 'Confirm AV / sound system availability and quality'),
    ('Space & Facilities', 'Check WiFi reliability (for DJ, photo booth, live-stream)'),
    ('Space & Facilities', 'Ask about power access for band, vendors, lighting'),
    ('Space & Facilities', 'Verify ADA / wheelchair accessibility throughout'),

    # Vendors
    ('Vendors', "Ask if there's a required or exclusive preferred vendor list"),
    ('Vendors', 'Confirm whether outside caterers are allowed'),
    ('Vendors', 'Understand alcohol policy and bartender requirements'),
    ('Vendors', 'Confirm if a day-of coordinator is included'),
    ('Vendors', 'Ask if on-site security is required (and at what cost)'),

    # Décor
    ('Décor', 'Ask if open-flame candles are permitted'),
    ('Décor', 'Check confetti, sparkler, and fireworks policy'),
    ('Décor', 'Ask about hanging décor / ceiling rigging restrictions'),
    ('Décor', 'Ask if real flower petals are allowed on the aisle'),

    # Guest Experience
    ('Guest Experience', 'Ask when the final headcount is due'),
    ('Guest Experience', 'Verify max capacity for both ceremony and reception layouts'),
    ('Guest Experience', 'Ask if coat check / bag storage is available'),

    # Day-of
    ('Day-of', 'Confirm exclusive use — no other events on your date'),
    ('Day-of', 'Get a dedicated day-of venue contact name & direct number'),
    ('Day-of', 'Schedule a final walkthrough 4–6 weeks before the date'),
]


def seed_items(apps, schema_editor):
    VenueChecklistItem = apps.get_model('vendors', 'VenueChecklistItem')
    VenueChecklistItem.objects.bulk_create([
        VenueChecklistItem(category=cat, text=text, order=i)
        for i, (cat, text) in enumerate(ITEMS)
    ])


def unseed_items(apps, schema_editor):
    apps.get_model('vendors', 'VenueChecklistItem').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_venue_checklist_item'),
    ]

    operations = [
        migrations.RunPython(seed_items, unseed_items),
    ]
