# Generated by Django 4.2.29 on 2026-05-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorphoto_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeoption',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Link to a Google Drive document (contract, quote, etc.)'),
        ),
        migrations.AddField(
            model_name='catereroption',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Link to a Google Drive document (contract, quote, etc.)'),
        ),
        migrations.AddField(
            model_name='entertainmentoption',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Link to a Google Drive document (contract, quote, etc.)'),
        ),
        migrations.AddField(
            model_name='floristoption',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Link to a Google Drive document (contract, quote, etc.)'),
        ),
        migrations.AddField(
            model_name='venueoption',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Link to a Google Drive document (contract, quote, etc.)'),
        ),
    ]
