# Generated by Django 4.2.29 on 2026-05-17 00:23

from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vendors', '0007_add_google_drive_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeoption',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='catereroption',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='entertainmentoption',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='floristoption',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='venueoption',
            name='google_drive_url',
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to=vendors.models._vendor_doc_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
