import type { Moment } from './types'

export interface Suggestion { title: string; artist: string }

export const SUGGESTIONS: Record<Moment, Suggestion[]> = {
  ceremony: [
    { title: 'Canon in D', artist: 'Pachelbel' },
    { title: 'A Thousand Years', artist: 'Christina Perri' },
    { title: 'Here Comes the Sun', artist: 'The Beatles' },
    { title: 'Can\'t Help Falling in Love', artist: 'Elvis Presley' },
    { title: 'Marry Me', artist: 'Train' },
    { title: 'Turning Page', artist: 'Sleeping at Last' },
    { title: 'Somewhere Over the Rainbow', artist: 'Israel Kamakawiwoʻole' },
    { title: 'Clair de Lune', artist: 'Debussy' },
    { title: 'Ave Maria', artist: 'Schubert' },
    { title: 'Grow Old with Me', artist: 'Tom Odell' },
    { title: 'The Book of Love', artist: 'Peter Gabriel' },
    { title: 'Bittersweet Symphony', artist: 'The Verve' },
  ],
  first_dance: [
    { title: 'Perfect', artist: 'Ed Sheeran' },
    { title: 'All of Me', artist: 'John Legend' },
    { title: 'Thinking Out Loud', artist: 'Ed Sheeran' },
    { title: 'At Last', artist: 'Etta James' },
    { title: 'The Way You Look Tonight', artist: 'Frank Sinatra' },
    { title: 'Make You Feel My Love', artist: 'Adele' },
    { title: 'Better Together', artist: 'Jack Johnson' },
    { title: 'Endless Love', artist: 'Lionel Richie & Diana Ross' },
    { title: 'La Vie en Rose', artist: 'Édith Piaf' },
    { title: 'Stand by Me', artist: 'Ben E. King' },
    { title: 'Unchained Melody', artist: 'The Righteous Brothers' },
    { title: 'To Make You Feel My Love', artist: 'Bob Dylan' },
  ],
  cocktail: [
    { title: 'Fly Me to the Moon', artist: 'Frank Sinatra' },
    { title: 'The Girl from Ipanema', artist: 'Astrud Gilberto' },
    { title: 'What a Wonderful World', artist: 'Louis Armstrong' },
    { title: 'Come Away with Me', artist: 'Norah Jones' },
    { title: 'Feeling Good', artist: 'Nina Simone' },
    { title: 'Moondance', artist: 'Van Morrison' },
    { title: 'Blue Skies', artist: 'Ella Fitzgerald' },
    { title: 'Dream a Little Dream of Me', artist: 'Ella Fitzgerald' },
    { title: 'The Best Is Yet to Come', artist: 'Frank Sinatra' },
    { title: 'Summertime', artist: 'Ella Fitzgerald' },
    { title: 'L-O-V-E', artist: 'Nat King Cole' },
    { title: 'Beyond the Sea', artist: 'Bobby Darin' },
  ],
  reception: [
    { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars' },
    { title: 'Can\'t Stop the Feeling!', artist: 'Justin Timberlake' },
    { title: 'September', artist: 'Earth, Wind & Fire' },
    { title: 'Dancing Queen', artist: 'ABBA' },
    { title: 'Don\'t Stop Believin\'', artist: 'Journey' },
    { title: 'Shake It Off', artist: 'Taylor Swift' },
    { title: 'Marry You', artist: 'Bruno Mars' },
    { title: 'I Gotta Feeling', artist: 'Black Eyed Peas' },
    { title: 'Livin\' on a Prayer', artist: 'Bon Jovi' },
    { title: 'Crazy in Love', artist: 'Beyoncé' },
    { title: 'Superstition', artist: 'Stevie Wonder' },
    { title: 'Happy', artist: 'Pharrell Williams' },
    { title: 'Love On Top', artist: 'Beyoncé' },
    { title: 'Treasure', artist: 'Bruno Mars' },
    { title: 'Can You Feel the Love Tonight', artist: 'Elton John' },
    { title: 'Mr. Brightside', artist: 'The Killers' },
  ],
  other: [
    { title: 'Best Day of My Life', artist: 'American Authors' },
    { title: 'Lovely Day', artist: 'Bill Withers' },
    { title: 'Walking on Sunshine', artist: 'Katrina and the Waves' },
    { title: 'You Are the Best Thing', artist: 'Ray LaMontagne' },
    { title: 'Lucky', artist: 'Jason Mraz & Colbie Caillat' },
    { title: 'I Do', artist: 'Colbie Caillat' },
    { title: 'From This Moment On', artist: 'Shania Twain' },
    { title: 'Signed, Sealed, Delivered', artist: 'Stevie Wonder' },
  ],
}
